### ISSUE TITLE
School Application - Question

### ISSUE THREAD

**Issue by svenstuh** [timtimmytime/ywam-staff-webapp-firebase#82]
When filling out a application I am asked a question but I don't seem to be able to read the hole sentence. 
<img width="755" alt="screen shot 2017-04-27 at 12 42 45 pm" src="https://cloud.githubusercontent.com/assets/24277937/25499804/aa06b40e-2b5a-11e7-8d84-866195000f8d.png">

**Comment by svenstuh** [comment]
And also with this one, maybe we can change the wording or take it out for YWAM Sarasota as applicants don't receive a residence permit. This could potentially get us in legal trouble I believe
<img width="477" alt="screen shot 2017-04-27 at 12 43 11 pm" src="https://cloud.githubusercontent.com/assets/24277937/25499861/e2c3d984-2b5a-11e7-8420-146c8f45b651.png">

**Comment by timtimmytime** [comment]
Removed extra text on passport info component & displayed question text above the md-input-container. Fixed in current version as of now.
